# Generated by Django 2.2.3 on 2019-07-26 16:27

import anime_importer_app.utils.file_validations
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=100)),
                ('episodes', models.IntegerField()),
                ('rating', models.FloatField()),
                ('members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y_%m_%d/%H:%M:%S', validators=[anime_importer_app.utils.file_validations.validator])),
            ],
        ),
        migrations.CreateModel(
            name='AnimeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('anime_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anime_importer_app.Anime')),
            ],
        ),
    ]
